### ISSUE TITLE
(oauth_)code empty with session store

### ISSUE THREAD

**Issue by rudesome** [simov/grant-azure#1]
Hello,

For educational purposes am trying out Azure functions and thought of a nice oauth proxy flow when i saw this grant-azure repository.

Am using the dynamic-state example which saves the session to firebase.

When i try the example it creates the entry in firebase, but won't save any oauth_code or code in the entry, it just stays empty, 
![dynamic_state_store](https://user-images.githubusercontent.com/26667983/124512002-b045be80-ddd7-11eb-8af1-d84e0276e768.png)

I tried with different kind of identity providers.
the authentication is correct cause am getting the tokens back in the browser once logged in, but nothing is saved in firebase...

I probably missing something essential.. Can you help me out or give me a hint?
Thanks

**Comment by rudesome** [comment]
Tested with AWS handler (worked perfectly with serverless, thanks for showing) it only registered: 

```json
{ 
  "id" : { 
    "grant" : {
      "provider": "google" 
    }
  }
}
```

---
this is specific to Azure functions cause of the requestOverrides
Guess you just need the id as reference and provider... 
Can't find any good information what should be stored in the session store and how to make use of it.

**Comment by simov** [comment]
The session in Grant is being used only during the OAuth flow. Grant stores whatever is [needed](https://github.com/simov/grant#callback-session) there for it to work. It's up to you to decide whether you want to use that session for anything else or not.

Some of the examples [here](https://github.com/simov/grant-azure#examples) in particular are using Firebase as external session store, just to showcase how can you hook up any external session store with the exposed `session` configuration in Grant.

The whole point of having external session store is to encode just the session ID inside your cookie, and have all other potentially sensitive data stored outside of it. You can use external session store with any of the examples presented here.

The goal of the examples here is to showcase two features mainly:
- [Transport Types](https://github.com/simov/grant#callback-transport)
- [Dynamic State Overrides](https://github.com/simov/grant#dynamic-state)

but any other concept presented in the main readme applies to, and can be used with any serverless handler that is supported.
